-- local regexplainer = require('regexplainer')
-- regexplainer.setup{
--     display = 'split',
--     -- popup = {
--     --     border = {
--     --         padding = {1, 2},
--     --         style = 'solid',
--     --     },
--     -- },
--     auto = true,
-- }
--
-- vim.keymap.set("n", "<leader>rr", regexplainer.toggle)
-- vim.keymap.set("n", "<leader>ry", "<CMD>RegexplainerYank +<CR>")
--
