-- vim.filetype.add({
--     extension = {
--         conf = "conf",
--         env = "dotenv",
--     },
--     filename = {
--         [".env"] = "dotenv",
--     },
--     pattern = {
--         ["%.env%.[%w_.-]+"] = "dotenv",
--     },
-- })
